services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Security\:
        resource: '../../src/AppBundle/Security/*'

    AppBundle\Security\TokenManager:
        public: true
        arguments:
            $validatationLogger: '@logger'
            $tokenSignatureKey:  'lOZjMX4mU2799pZ0WCCW0Lx0ftlTTMhDSzt5bZu4'
        tags:
            - { name: monolog.logger, channel: validation }